; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36248.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
msvcjmc	SEGMENT
__5C2A3A1B_concurrencysal@h DB 01H
__C0F69881_sal@h DB 01H
__78278261_vadefs@h DB 01H
__B7ABD719_vcruntime@h DB 01H
__53769204_xkeycheck@h DB 01H
__A0070F5A_yvals_core@h DB 01H
__735960E1_corecrt@h DB 01H
__CB8A55F3_float@h DB 01H
__DC7B723E_cfloat DB 01H
__BE5CC238_limits@h DB 01H
__C5D0737A_climits DB 01H
__632B5AB7___msvc_doom_core@hpp DB 01H
__E737CACB_vcruntime_new@h DB 01H
__5C5D34C3_vcruntime_new_debug@h DB 01H
__15FC02C9_crtdbg@h DB 01H
__236569A6_crtdefs@h DB 01H
__2356D53E_use_ansi@h DB 01H
__F77FE737_yvals@h DB 01H
__1D9A7FA2_corecrt_math@h DB 01H
__2E93F1C0_math@h DB 01H
__211DB995_corecrt_malloc@h DB 01H
__955456CD_stddef@h DB 01H
__99AED4FB_corecrt_search@h DB 01H
__8B813BF6_corecrt_wstdlib@h DB 01H
__E8FB0A68_stdlib@h DB 01H
__413F5188_cstdlib DB 01H
__D858E777_xtr1common DB 01H
__231E93D5_intrin0@inl@h DB 01H
__3A48D0AD_intrin0@h DB 01H
__E4F48B25_cstddef DB 01H
__002AEC07_stdint@h DB 01H
__FC61B0F5_cstdint DB 01H
__1DDF54CF_type_traits DB 01H
__A24C9636_cmath DB 01H
__60B45B40_corecrt_stdio_config@h DB 01H
__CFA3741E_corecrt_wstdio@h DB 01H
__B3FE3303_stdio@h DB 01H
__AF3FB9B9_cstdio DB 01H
__13DE2371_errno@h DB 01H
__A8C627D8_vcruntime_string@h DB 01H
__8ACB2152_corecrt_memcpy_s@h DB 01H
__EA6C9D17_corecrt_memory@h DB 01H
__0DF2AF52_corecrt_wstring@h DB 01H
__6E889ECC_string@h DB 01H
__0DADF968_cstring DB 01H
__8BDC0229_corecrt_wconio@h DB 01H
__108B2620_corecrt_wctype@h DB 01H
__547F429B_corecrt_wdirect@h DB 01H
__260A2221_corecrt_share@h DB 01H
__EB642103_corecrt_wio@h DB 01H
__F49D648E_corecrt_wprocess@h DB 01H
__9E5BC8DA_corecrt_wtime@h DB 01H
__2A5E3E75_types@h DB 01H
__B16B2B9B_stat@h DB 01H
__90490404_setjmp@h DB 01H
__E6767EBD_mmintrin@h DB 01H
__7CD62D9E_malloc@h DB 01H
__377EBB4D_xmmintrin@h DB 01H
__521C3281_emmintrin@h DB 01H
__8DBD5A08_pmmintrin@h DB 01H
__3D64298A_tmmintrin@h DB 01H
__145F3C09_smmintrin@h DB 01H
__713DB5C5_nmmintrin@h DB 01H
__A4864F8B_wmmintrin@h DB 01H
__6F12028C_zmmintrin@h DB 01H
__5806A046_immintrin@h DB 01H
__E2C54103_ammintrin@h DB 01H
__B67FB873_intrin@h DB 01H
__4DD8D0FE_wchar@h DB 01H
__35B46FEA_cwchar DB 01H
__7674EADC_iosfwd DB 01H
__46EC4C28_initializer_list DB 01H
__E85A7D30_concepts DB 01H
__B82A6B39_compare DB 01H
__7632D403_utility DB 01H
__6D87F1DA___msvc_iter_core@hpp DB 01H
__6CF294FA_xutility DB 01H
__7D5E23BA_iterator DB 01H
__85852BDB_share@h DB 01H
__F50AA420___msvc_system_error_abi@hpp DB 01H
__321ECD42_cerrno DB 01H
__C071288D_corecrt_terminate@h DB 01H
__6BA7D6F9_eh@h DB 01H
__54B33191_vcruntime_exception@h DB 01H
__EB3A0730_exception DB 01H
__40B7BB17___msvc_sanitizer_annotate_container@hpp DB 01H
__6AD86124___msvc_string_view@hpp DB 01H
__BA9D3F5A_limits DB 01H
__67CB75C4_new DB 01H
__E1368BE6_xatomic@h DB 01H
__046F8F77_tuple DB 01H
__1CA7B7C0_xmemory DB 01H
__FDFB76D3_xpolymorphic_allocator@h DB 01H
__6874315C_xstring DB 01H
__62743D6D_stdexcept DB 01H
__E39FD10A_xcall_once@h DB 01H
__5FEAF238_xerrc@h DB 01H
__7CE95A3B___msvc_threads_core@hpp DB 01H
__1FF36214_time@h DB 01H
__64FF0A3E_ctime DB 01H
__DA3677BB_xtimec@h DB 01H
__4218E28D_xthreads@h DB 01H
__BB3AF5A5_xatomic_wait@h DB 01H
__D1A86398_atomic DB 01H
__5CC2C32A_system_error DB 01H
__79691745_vcruntime_typeinfo@h DB 01H
__1C2D67E3_typeinfo DB 01H
__063333D4_memory DB 01H
__2A7664DB_xfacet DB 01H
__A019BBA1___msvc_xlocinfo_types@hpp DB 01H
__6CD6613D_ctype@h DB 01H
__A0F45E1E_cctype DB 01H
__FFBDF365_locale@h DB 01H
__D2938D59_clocale DB 01H
__03A4842B_xlocinfo DB 01H
__B74A456D_xlocale DB 01H
__3A41F338_xiosbase DB 01H
__60D485D1_streambuf DB 01H
__29CD237A_xlocnum DB 01H
__9F064FD2_ios DB 01H
__24703A34___msvc_ostream@hpp DB 01H
__C78AAA93_istream DB 01H
__A45A9FA9_ostream DB 01H
__0E8BEEE5_iostream DB 01H
__69CAA4C4_Main@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z ; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z ; __empty_global_delete
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0N@GCDOMLDM@Hello?5World?$CB@		; `string'
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ:PROC
EXTRN	?Log@@YAXPEBD@Z:PROC				; Log
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN4
	DD	imagerel $LN4+34
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN4
	DD	imagerel $LN4+39
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z DD imagerel $LN4
	DD	imagerel $LN4+39
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z DD imagerel $LN4
	DD	imagerel $LN4+44
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+59
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0N@GCDOMLDM@Hello?5World?$CB@
CONST	SEGMENT
??_C@_0N@GCDOMLDM@Hello?5World?$CB@ DB 'Hello World!', 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025030b01H
	DD	0b206230bH
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z DD 025031901H
	DD	0b2142319H
	DD	05010H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z DD 025031401H
	DD	0b20f2314H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025031401H
	DD	0b20f2314H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025030f01H
	DD	0b20a230fH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 80
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\f!xcs\Desktop\C++\Learning-C-\HelloWorld\HelloWorld\Main.cpp
; Line 11
$LN4:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__69CAA4C4_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 80
__formal$ = 88
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\f!xcs\Desktop\C++\Learning-C-\HelloWorld\HelloWorld\Main.cpp
; Line 11
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__69CAA4C4_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z
_TEXT	SEGMENT
__formal$ = 80
__formal$ = 88
?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z PROC ; __empty_global_delete, COMDAT
; File C:\Users\f!xcs\Desktop\C++\Learning-C-\HelloWorld\HelloWorld\Main.cpp
; Line 11
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__69CAA4C4_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAXW4align_val_t@std@@@Z ENDP ; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z
_TEXT	SEGMENT
__formal$ = 80
__formal$ = 88
__formal$ = 96
?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z PROC ; __empty_global_delete, COMDAT
; File C:\Users\f!xcs\Desktop\C++\Learning-C-\HelloWorld\HelloWorld\Main.cpp
; Line 11
$LN4:
	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__69CAA4C4_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_KW4align_val_t@std@@@Z ENDP ; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File C:\Users\f!xcs\Desktop\C++\Learning-C-\HelloWorld\HelloWorld\Main.cpp
; Line 7
$LN3:
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__69CAA4C4_Main@cpp
	call	__CheckForDebuggerJustMyCode
	npad	1
; Line 8
	lea	rcx, OFFSET FLAT:??_C@_0N@GCDOMLDM@Hello?5World?$CB@
	call	?Log@@YAXPEBD@Z				; Log
	npad	1
; Line 9
	mov	rcx, QWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	QWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ
	npad	1
; Line 10
	xor	eax, eax
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
END
